function n = compute_normals(pc)
global glob;
    %% tangential vectors computation
    x = reshape(pc(:,1),glob.H,glob.W);
    y = reshape(pc(:,2),glob.H,glob.W);
    z = reshape(pc(:,3),glob.H,glob.W);
    xxdiff = x(2:end,3:end)-x(2:end,1:end-2);
    xydiff = y(2:end,3:end)-y(2:end,1:end-2);
    xzdiff = z(2:end,3:end)-z(2:end,1:end-2);
    yxdiff = x(3:end,2:end)-x(1:end-2,2:end);
    yydiff = y(3:end,2:end)-y(1:end-2,2:end);
    yzdiff = z(3:end,2:end)-z(1:end-2,2:end);
    %% integral images of the tangential vectors (x,y,z, components)
    xxI = integralImage(xxdiff);
    xyI = integralImage(xydiff);
    xzI = integralImage(xzdiff);
    yxI = integralImage(yxdiff);
    yyI = integralImage(yydiff);
    yzI = integralImage(yzdiff);
    tI = cat(3,[xxI,xxI(:,end)],[xyI,xyI(:,end)],[xzI,xzI(:,end)],...
        [yxI;yxI(end,:)],[yyI;yyI(end,:)],[yzI;yzI(end,:)]);
    %% average tangential vectors
    
    avgTI = zeros(size(tI,1)-glob.wy,size(tI,2)-glob.wx,size(tI,3));
    for j=1:size(tI,3)
        avgTI(:,:,j) = (tI(glob.wy+1:end,glob.wx+1:end,j)-...
            tI(glob.wy+1:end,1:end-glob.wx,j)-...
            tI(1:end-glob.wy,glob.wx+1:end,j)+...
            tI(1:end-glob.wy,1:end-glob.wx,j))/glob.wy/glob.wx;
    end
    txx = [zeros(ceil(glob.wy/2),glob.W);...
        zeros(size(avgTI,1),ceil(glob.wx/2)),...
        avgTI(:,:,1),zeros(size(avgTI,1),...
        floor(glob.wx/2)); zeros(floor(glob.wy/2),glob.W)];
    txy = [zeros(ceil(glob.wy/2),glob.W);...
        zeros(size(avgTI,1),ceil(glob.wx/2)),...
        avgTI(:,:,2),zeros(size(avgTI,1),...
        floor(glob.wx/2)); zeros(floor(glob.wy/2),glob.W)];
    txz = [zeros(ceil(glob.wy/2),glob.W);...
        zeros(size(avgTI,1),ceil(glob.wx/2)),...
        avgTI(:,:,3),zeros(size(avgTI,1),...
        floor(glob.wx/2)); zeros(floor(glob.wy/2),glob.W)];
    tyx = [zeros(ceil(glob.wy/2),glob.W);...
        zeros(size(avgTI,1),ceil(glob.wx/2)),...
        avgTI(:,:,4),zeros(size(avgTI,1),...
        floor(glob.wx/2)); zeros(floor(glob.wy/2),glob.W)];
    tyy = [zeros(ceil(glob.wy/2),glob.W);...
        zeros(size(avgTI,1),ceil(glob.wx/2)),...
        avgTI(:,:,5),zeros(size(avgTI,1),...
        floor(glob.wx/2)); zeros(floor(glob.wy/2),glob.W)];
    tyz = [zeros(ceil(glob.wy/2),glob.W);...
        zeros(size(avgTI,1),ceil(glob.wx/2)),...
        avgTI(:,:,6),zeros(size(avgTI,1),...
        floor(glob.wx/2)); zeros(floor(glob.wy/2),glob.W)];
	tx = cat(3,txx,txy,txz);
	ty = cat(3,tyx,tyy,tyz);
    
    %% normals
    n = cross(tx,ty,3);
end
    